### ISSUE TITLE
Android intents URL on README is 404ing

### ISSUE THREAD

**Issue by alexbain** [pebble/pebblekit#1]
"It is also possible to send standard, text-based notifications to Pebble without writing a custom watch app, by using the Android Intent API. More information can be found here: http://developer.getpebble.com/android/intents"

Tries to load: http://developer.getpebble.com/1/03_API_Reference/03_AndroidIntents

Which is a 404.

**Comment by martijnthe** [comment]
Thanks for catching, about to be fixed.

**Comment by imax9000** [comment]
Still 404.

**Comment by ppareit** [comment]
Still 404!
