### ISSUE TITLE
APP_TIMER_INVALID_HANDLE not defined

### ISSUE THREAD

**Issue by Katharine** [pebble/pebblekit#10]
The documentation claims that timers can return `APP_TIMER_INVALID_HANDLE` instead of actually creating a timer (though not why or when). This value isn't actually defined.

The documentation does helpfully include the missing line, though:

``` c
#define APP_TIMER_INVALID_HANDLE   ((AppTimerHandle)0)
```

**Comment by iosdeveloper** [comment]
Fixed in v1.12. You may close this issue.
