### ISSUE TITLE
Text rendering distorts characters crossing the y axis of their frame

### ISSUE THREAD

**Issue by Katharine** [pebble/pebblekit#12]
As a character crosses _x_ = 0 of the frame it is being rendered in, the character becomes increasingly distorted. At one position it will actually render on the other side of the screen, outside the right edge of the layer it's supposed to render in.

(this is an issue for my marquee text layers, which currently use a workaround by changing the bounds of the frame and drawing white rectangles over the glitches)

I have provided a demo program [here](https://gist.github.com/Katharine/5677054); use up and down to move the text left and right and see it break. You can also grab a [compiled version](http://builds.cloudpebble.net/2/9/295b94c3940e4346aae86abf78c0d6a7/watchface.pbw).

Some pictures:
![img_0442](https://f.cloud.github.com/assets/110792/584373/7ec40e32-c915-11e2-96a1-38a7680f8b44.jpg)
![img_0443](https://f.cloud.github.com/assets/110792/584378/991386fa-c915-11e2-8faa-d0ba64e568dd.jpg)

**Comment by nitinguptadr** [comment]
Not an issue on 3.X master as of today.
