### ISSUE TITLE
GTextOverflowMode lacks documentation

### ISSUE THREAD

**Issue by iosdeveloper** [pebble/pebblekit#18]
https://developer.getpebble.com/sdkref/group___text_drawing.html#gadad5abc1b1cfbddd48bd79f70c05b8fa

**Comment by AlexKeySmith** [comment]
I'd be interested in this to.

**Comment by iosdeveloper** [comment]
From pebble_os.h:

`typedef enum {GTextOverflowModeWordWrap, GTextOverflowModeTrailingEllipsis} GTextOverflowMode;`

**Comment by sjvanrossum** [comment]
WordWrap should wrap until the last word that fully fits the width and jump to the next line.
TrailingEllipsis should cut off the text, leaving dots at the end to indicate there's more content.

**Comment by iosdeveloper** [comment]
SDK 2.0 adds `GTextOverflowModeFill`. Anyone mind telling how it should behave?

@JvetS

**Comment by sjvanrossum** [comment]
No clue yet, I'll be fiddling with 2.0 for the first time this afternoon.
You could just write a sample and check it out.

**Comment by iosdeveloper** [comment]
Fixed in v2.0-BETA2.

**Comment by sarfata** [comment]
Hey @iosdeveloper - Thanks for taking the time to close these - awesome!
