### ISSUE TITLE
[Pebble] menu_layer_get_selected_index() missing from the header

### ISSUE THREAD

**Issue by iosdeveloper** [pebble/pebblekit#22]
`menu_layer_get_selected_index()` is missing from the header, although it is documented: https://developer.getpebble.com/sdkref/group___menu_layer.html#ga21d029fa677fade062d63faea1f29a33

**Comment by martijnthe** [comment]
Thanks for catching this. Will be fixed in next update.

**Comment by iosdeveloper** [comment]
Fixed in v1.12. Thanks!
