### ISSUE TITLE
[iOS] 'Open in' only works after Pebble app has launched

### ISSUE THREAD

**Issue by iosdeveloper** [pebble/pebblekit#30]
'Open in' should also be handled in `application:didFinishLaunchingWithOptions:` in the official Pebble iOS app, so we can open our watch apps in the Pebble app for the user to install.

**Comment by martijnthe** [comment]
Not exactly sure what you mean. This should already be working. Please elaborate. Thanks.

**Comment by iosdeveloper** [comment]
You can try this yourself. Exit the Pebble app in the multitasking bar. Load a pbw e.g. from MyPebbleFaces in Safari and open in Pebble. It won't prompt you to install. Now that the app has been launched, try it again. It'll work..

**Comment by iosdeveloper** [comment]
Fixed in v1.2. Thanks!
