### ISSUE TITLE
vibes_cancel permanently disables vibration.

### ISSUE THREAD

**Issue by matthewtole** [pebble/pebblekit#36]
Perhaps I'm misusing it, or misunderstand what vibes_cancel() is supposed to do, but whenever I use it, it seems to disable vibration entirely on the Pebble until I restart it. 

From the documentation, I assume that vibes_cancel() is just supposed to stop any currently ongoing or queued vibrations.

**Comment by tommaremaa** [comment]
Matthew, can you please this issue in a bit more detail? I'd like to document the behavior correctly. Thx.

**Comment by matthewtole** [comment]
Sure.

The function vibes_cancel, as [documented here](http://developer.getpebble.com/sdkref/group___vibes.html), I think is supposed to stop any currently running vibrations, for example if you have a really long vibration or pattern of vibrations it will end it early.

Whenever I call it, it does what it's supposed to, but then my watch won't vibrate **_at all**_ until I shut it down and start up again. I tried notifications + other apps, none of them would make the watch vibrate. It should be pretty easy to replicate, just call vibes_cancel() in an app.
