### ISSUE TITLE
[iOS] Pebble app: Remove pbw after installation

### ISSUE THREAD

**Issue by iosdeveloper** [pebble/pebblekit#39]
The pbw of every watchface ever opened in the Pebble iOS app is kept in the Documents Inbox directory. Since this directory cannot be accessed by the user anyway, these files occupy memory unnecessarily and should be removed right after installation.

**Comment by iosdeveloper** [comment]
Source: http://forums.getpebble.com/discussion/comment/55760/#Comment_55760

@martijnthe

**Comment by Haifisch** [comment]
Agreed; This is a simple fix, and just good app etiquette.

**Comment by iosdeveloper** [comment]
Still appears to be in 2.0-BETA6.

@sarfata

**Comment by JaviSoto** [comment]
This will be fixed on the next release. Thanks for reporting!

**Comment by iosdeveloper** [comment]
@JaviSoto Watchapps that are [opened in the Pebble iOS app from another iOS app](https://github.com/pebble-hacks/iOS-Installer) are still kept in Documents/Inbox in 2.0-BETA7. They should be moved to the Caches directory as well.

**Comment by JaviSoto** [comment]
This will be fixed on a future release, sorry about that.
