### ISSUE TITLE
Native HTTP support

### ISSUE THREAD

**Issue by natevw** [pebble/pebblekit#41]
Would love to see Pebble Kit get official support for HTTP along the lines of what Katharine has done with HTTPebble. There's already a [branch of libpebble](https://github.com/aleksandyr/libpebble/) that supports the protocol, and I've been [gathering some notes](https://github.com/Katharine/httpebble-watch/issues/4) on how to tweak the current protocol to be a bit more efficient. (I've also been researching [CoAP](http://en.wikipedia.org/wiki/Constrained_Application_Protocol) quite a bit with my [microstates](https://github.com/natevw/microstates) project and there's some good stuff there that might be worth using in a "2.0" implementation.)

I found HTTPebble to be a really compelling "platform" for a watch app. It has some drawbacks in that it requires a second app to be installed and kept running by the user, some UUID issues, and the creator/maintainer seems to be very busy with paying work. These drawbacks could go away with official support, and to do so would make shipping really interesting watch apps much easier. Would love to see her get some official work with "the mothership" :-)

**Comment by iosdeveloper** [comment]
:+1:

**Comment by sarfata** [comment]
Hi @natevw 

Thanks for the feedback. I am going to close this now as this is not really a bug. 

Totally unrelated: Please contact me (thomas@getpebble.com) if you would like to check out the new SDK under NDA.

thomas

**Comment by bengalaviz** [comment]
:+1:

**Comment by natevw** [comment]
Thanks guys :-)

**Comment by natevw** [comment]
To clarify: 1) the [PebbleKit JS framework](https://developer.getpebble.com/2/guides/javascript-guide.html) will make it possible to make HTTP requests without a separate app (and without UUID hacks), and 2) in this morning's announcements [mention was made](http://www.youtube.com/watch?v=uoVX2ibCFXw#t=453) that Pebble is sponsoring Katherine — so, best of both worlds!
