### ISSUE TITLE
No documentation for time_t pbl_override_time(time_t *tloc)

### ISSUE THREAD

**Issue by sjvanrossum** [pebble/pebblekit#47]
No documentation available for `time_t pbl_override_time(time_t *tloc)`.
What does it do, why should one use it?
As far as I understand it should replace the current time value with the given time value?

**Comment by Meiguro** [comment]
I believe this is the time function as it has the same prototype and isn't actually callable, so it must have been accidentally included in pebble_os.h. Originally time wasn't usable as gcc would fail to include it as a builtin function. Hopefully it will be removed in a future SDK release.
