### ISSUE TITLE
[iOS] Crash when opening pbw in Pebble app

### ISSUE THREAD

**Issue by iosdeveloper** [pebble/pebblekit#51]
iOS Pebble app crashes when a pbw is opened in it. Doesn't crash only when navigated to the list of installed watchapps before opening the pbw in Pebble.

**Comment by iosdeveloper** [comment]
@martijnthe

**Comment by cjwilliams** [comment]
An internal bug (PBL-1008) has been logged for this, thanks!

**Comment by wello007** [comment]
Hello

Any update on this? I am not able to install anything. I sthere an alternative?

**Comment by varsy** [comment]
Same behaviour on my phone, after opening from safari.

**Comment by iosdeveloper** [comment]
Apparently fixed in 2.0-BETA2.

**Comment by varsy** [comment]
Thank you, validated.
