### ISSUE TITLE
Including Cocoa Lumberjack inside this project makes it hard to embed

### ISSUE THREAD

**Issue by rustyshelf** [pebble/pebblekit#59]
The Pebble iOS SDK has a podspec already, why not just list Cocoa Lumberjack as a dependency to that? As it stands if I embed your framework and another that also requires Cocoa Lumberjack I can't compile the project:

The specific error:
duplicate symbol _OBJC_METACLASS_$_DDTTYLoggerColorProfile in:
    /Users/rustyshelf/pebble-dev/PebbleSDK-2.0.1/PebbleKit-iOS/PebbleVendor.framework/PebbleVendor(DDTTYLogger.o)
    /Users/rustyshelf/Library/Developer/Xcode/DerivedData/RustyX-cmywtluwsmsmaxfxtzuhlaltmuiq/Build/Products/Debug-iphonesimulator/libPods.a(DDTTYLogger.o)
ld: 88 duplicate symbols for architecture i386

**Comment by sarfata** [comment]
You can just remove lumberjack from the PebbleVendor project. That is exactly why we put all our dependencies in there. 

We do want to get a better official podspec, until we do you can use the one by @hbehrens: https://github.com/CocoaPods/Specs/blob/master/PebbleKit/2.0.1/PebbleKit.podspec

**Comment by ssuchanowski** [comment]
is there any fix for that?

**Comment by sarfata** [comment]
The best solution right now is to not use CocoaPod, manually add PebbleKit and PebbleVendor to your project and remove lumberjack from the PebbleVendor project.

**Comment by fraggle222** [comment]
Still having trouble with this.

**Comment by fraggle222** [comment]
@sarfata Do you have a sample project with PebbleKit installed manually and PebbleVendor project included without Lumberjack? I've been trying to produce that and I'm getting build errors.

**Comment by ssuchanowski** [comment]
Pebble repo doesn't seem to updated for a while now (year, sick!) so I don't think that anything changed in this manner.
