### ISSUE TITLE
ClickConfig::long_click.release_handler doesn't seem to to get called from ActionBarLayers

### ISSUE THREAD

**Issue by llamahunter** [pebble/pebblekit#8]
I have a long_click.release_handler attached to an ActionBarLayer, along with a click.handler and long_click.handler.  The latter two are called as expected.  The former is not.  When using direct ClickConfig on a window, the release_handler is called.  I suspect the ActionBarLayer is intercepting the button release to remove the InverterLayer over the selected button icon, and not passing it on to the user configured handler.

**Comment by martijnthe** [comment]
@llamahunter, can you post a gist with a sample app that reproduces this bug?
Thanks.

**Comment by llamahunter** [comment]
Sorry, been out of town.  Will make a small reproducible case this weekend.

**Comment by llamahunter** [comment]
Ok, so it's definitely reproducible in a small test case.  However, I did find that it is important to change the icon on the action bar in the long press callback to have it fail to call you back on long press release.  If you leave the icons unchanged, the release callback _is_ called.  However, if you want to give the user feedback that they have held the button down long enough for it to be interpreted as a long press (by changing the icon), you never get a message when the button is released so that you can change the button back.

If you'd like a copy of the app and full source, please let me know where to upload it.  In the meantime, you can find the gist here at http://pastebin.com/JHnSbGp0

The resource_map.json is a trivial list of six 16x16 png images for use in the action bar.

**Comment by martijnthe** [comment]
For the record, copied the code on http://pastebin.com/JHnSbGp0 here:

<pre>
#include "pebble_os.h"
#include "pebble_app.h"
#include "pebble_fonts.h"
 
#include "resource_ids.auto.h"
 
#define MY_UUID { 0x23, 0x86, 0x9E, 0xFF, 0x9A, 0xAA, 0x44, 0xFD, 0x82, 0xBF, 0x73, 0xE8, 0x97, 0x64, 0xDA, 0xDF }
PBL_APP_INFO(MY_UUID,
             "Action Bar Test", "Acme Inc.",
             1, 0, /* App version */
             DEFAULT_MENU_ICON,
             APP_INFO_STANDARD_APP);
 
Window window;
TextLayer textLayer;
TextLayer responseLayer;
ActionBarLayer actionBarLayer;
HeapBitmap upBitmap;
HeapBitmap longupBitmap;
HeapBitmap downBitmap;
HeapBitmap longdownBitmap;
HeapBitmap selectBitmap;
HeapBitmap longselectBitmap;
 
void longupHandler(ClickRecognizerRef recognizer, void *context)
{
  text_layer_set_text(&responseLayer, "Up Long!");
  action_bar_layer_set_icon(&actionBarLayer, BUTTON_ID_UP, &longupBitmap.bmp);
}
 
void endLongupHandler(ClickRecognizerRef recognizer, void *context)
{
  text_layer_set_text(&responseLayer, "Up Release!");
  action_bar_layer_set_icon(&actionBarLayer, BUTTON_ID_UP, &upBitmap.bmp);
}
 
void longdownHandler(ClickRecognizerRef recognizer, void *context)
{
  text_layer_set_text(&responseLayer, "Down Long!");
  action_bar_layer_set_icon(&actionBarLayer, BUTTON_ID_DOWN, &longdownBitmap.bmp);
}
 
void endLongdownHandler(ClickRecognizerRef recognizer, void *context)
{
  text_layer_set_text(&responseLayer, "Down Release!");
  action_bar_layer_set_icon(&actionBarLayer, BUTTON_ID_DOWN, &downBitmap.bmp);
}
 
void longselectHandler(ClickRecognizerRef recognizer, void *context)
{
  text_layer_set_text(&responseLayer, "Select Long!");
  action_bar_layer_set_icon(&actionBarLayer, BUTTON_ID_SELECT, &longselectBitmap.bmp);
}
 
void endLongselectHandler(ClickRecognizerRef recognizer, void *context)
{
  text_layer_set_text(&responseLayer, "Select Release!");
  action_bar_layer_set_icon(&actionBarLayer, BUTTON_ID_SELECT, &selectBitmap.bmp);
}
 
void upHandler(ClickRecognizerRef recognizer, void *context)
{
  text_layer_set_text(&responseLayer, "Up!");
}
 
void downHandler(ClickRecognizerRef recognizer, void *context)
{
  text_layer_set_text(&responseLayer, "Down!");
}
 
void selectHandler(ClickRecognizerRef recognizer, void *context)
{
  text_layer_set_text(&responseLayer, "Select!");
}
 
void clickConfigProvider(ClickConfig **config, void *context)
{
  config[BUTTON_ID_UP]->click.handler = upHandler;
  config[BUTTON_ID_DOWN]->click.handler = downHandler;
  config[BUTTON_ID_SELECT]->click.handler = selectHandler;
  config[BUTTON_ID_UP]->long_click.handler = longupHandler;
  config[BUTTON_ID_UP]->long_click.delay_ms = 750;
  config[BUTTON_ID_UP]->long_click.release_handler = endLongupHandler;
  config[BUTTON_ID_DOWN]->long_click.handler = longdownHandler;
  config[BUTTON_ID_DOWN]->long_click.delay_ms = 750;
  config[BUTTON_ID_DOWN]->long_click.release_handler = endLongdownHandler;
  config[BUTTON_ID_SELECT]->long_click.handler = longselectHandler;
  config[BUTTON_ID_SELECT]->long_click.delay_ms = 750;
  config[BUTTON_ID_SELECT]->long_click.release_handler = endLongselectHandler;
}
 
void unloadWindow(Window *pWindow)
{
  heap_bitmap_deinit(&longupBitmap);
  heap_bitmap_deinit(&longdownBitmap);
  heap_bitmap_deinit(&longselectBitmap);
  heap_bitmap_deinit(&upBitmap);
  heap_bitmap_deinit(&downBitmap);
  heap_bitmap_deinit(&selectBitmap);
}
 
void handle_init(AppContextRef ctx) {
  (void)ctx;
 
  resource_init_current_app(&ACTIONBAR_APP_RESOURCES);
 
  window_init(&window, "Action Bar");
  WindowHandlers handlers = {
    .unload = unloadWindow
  };
  window_set_window_handlers(&window, handlers);
 
  GRect rect;
  rect.origin.x = 0;
  rect.size.w = 100;
  GFont font;
 
  font = fonts_get_system_font(FONT_KEY_GOTHIC_28_BOLD);
  rect.origin.y = 0;
  rect.size.h = 85;
  text_layer_init(&textLayer, rect);
  text_layer_set_font(&textLayer, font);
  text_layer_set_overflow_mode(&textLayer, GTextOverflowModeWordWrap);
  text_layer_set_text(&textLayer, "Press a Button");
  layer_add_child(&window.layer, &textLayer.layer);  
 
  font = fonts_get_system_font(FONT_KEY_GOTHIC_24);
  rect.origin.y += rect.size.h + 4;
  rect.size.h = 60;
  text_layer_init(&responseLayer, rect);
  text_layer_set_font(&responseLayer, font);
  text_layer_set_overflow_mode(&responseLayer, GTextOverflowModeWordWrap);
  text_layer_set_text(&responseLayer, "");
  layer_add_child(&window.layer, &responseLayer.layer);  
 
  action_bar_layer_init(&actionBarLayer);
  action_bar_layer_add_to_window(&actionBarLayer, &window);
  action_bar_layer_set_click_config_provider(&actionBarLayer, clickConfigProvider);
  heap_bitmap_init(&longupBitmap, RESOURCE_ID_LONGUP_ICON);
  heap_bitmap_init(&longdownBitmap, RESOURCE_ID_LONGDOWN_ICON);
  heap_bitmap_init(&selectBitmap, RESOURCE_ID_SELECT_ICON);
  heap_bitmap_init(&downBitmap, RESOURCE_ID_DOWN_ICON);
  heap_bitmap_init(&upBitmap, RESOURCE_ID_UP_ICON);
  heap_bitmap_init(&longselectBitmap, RESOURCE_ID_LONGSELECT_ICON);
  action_bar_layer_set_icon(&actionBarLayer, BUTTON_ID_UP, &upBitmap.bmp);
  action_bar_layer_set_icon(&actionBarLayer, BUTTON_ID_DOWN, &downBitmap.bmp);
  action_bar_layer_set_icon(&actionBarLayer, BUTTON_ID_SELECT, &selectBitmap.bmp);
 
  window_stack_push(&window, true);
}
 
 
void pbl_main(void *params) {
  PebbleAppHandlers handlers = {
    .init_handler = &handle_init
  };
  app_event_loop(params, &handlers);
}
</pre>

**Comment by llamahunter** [comment]
Any progress on reproducing and fixing?

**Comment by martijnthe** [comment]
Can you try doing all your layout + adding the action bar in a window.load handler?

**Comment by llamahunter** [comment]
Um... Not sure how that's going to make a difference, since the problem occurs long after the window is constructed.

Just tried it moving window layout + action bar to a load handler.  Still broken.

**Comment by llamahunter** [comment]
You've got the source code for a reproducible test case that I provided up there.  Why not try it in whatever debugger you have for the SDK implementation and figure out why the release callbacks aren't called?

**Comment by martijnthe** [comment]
Will be fixed in next release.
